/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
import type * as oracleLibrarySol from "./OracleLibrary.sol";
export type { oracleLibrarySol };
import type * as paymasterSol from "./Paymaster.sol";
export type { paymasterSol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { IWallet } from "./IWallet";
export type { Increment } from "./Increment";
export type { SubscriptionService } from "./SubscriptionService";
export type { Wallet } from "./Wallet";
export type { WalletFactory } from "./WalletFactory";
