/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  GaslessFaucet,
  GaslessFaucetInterface,
} from "../../../contracts/Faucet.sol/GaslessFaucet";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "Dripped",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "drip",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getTrustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610034737a95fa73250dc53556d264522150a940d4c5023861003960201b60201c565b61007c565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b61033e8061008b6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063572b6c0514610046578063ce1b815f14610076578063eb3839a714610094575b600080fd5b610060600480360381019061005b919061023b565b6100b0565b60405161006d9190610283565b60405180910390f35b61007e610109565b60405161008b91906102ad565b60405180910390f35b6100ae60048036038101906100a991906102c8565b610132565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16149050919050565b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b8173ffffffffffffffffffffffffffffffffffffffff1663cabee26e826040518263ffffffff1660e01b815260040161016b91906102ad565b600060405180830381600087803b15801561018557600080fd5b505af1158015610199573d6000803e3d6000fd5b505050507f989aa3afc5d5336c646d1e824888b072e19aad50714104ddf321d04d936f6640816040516101cc91906102ad565b60405180910390a15050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610208826101dd565b9050919050565b610218816101fd565b811461022357600080fd5b50565b6000813590506102358161020f565b92915050565b600060208284031215610251576102506101d8565b5b600061025f84828501610226565b91505092915050565b60008115159050919050565b61027d81610268565b82525050565b60006020820190506102986000830184610274565b92915050565b6102a7816101fd565b82525050565b60006020820190506102c2600083018461029e565b92915050565b600080604083850312156102df576102de6101d8565b5b60006102ed85828601610226565b92505060206102fe85828601610226565b915050925092905056fea264697066735822122020e7d1950e7dffe0c39d340398d4d363140b11125e628b12531052fc1797a7e464736f6c63430008110033";

type GaslessFaucetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GaslessFaucetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GaslessFaucet__factory extends ContractFactory {
  constructor(...args: GaslessFaucetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<GaslessFaucet> {
    return super.deploy(overrides || {}) as Promise<GaslessFaucet>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): GaslessFaucet {
    return super.attach(address) as GaslessFaucet;
  }
  override connect(signer: Signer): GaslessFaucet__factory {
    return super.connect(signer) as GaslessFaucet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GaslessFaucetInterface {
    return new utils.Interface(_abi) as GaslessFaucetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GaslessFaucet {
    return new Contract(address, _abi, signerOrProvider) as GaslessFaucet;
  }
}
